### ISSUE TITLE
ipfs upload from here

### ISSUE THREAD

**Issue by sakulstra** [bgd-labs/aave-proposals#85]
Currently ppl have to interact with https://github.com/aave/aip to upload theit aip.

For v2 the goal would be to somehow integrate an aip/ipfs upload process into this repository directly.
Some issues on aip repo, we should try to avoid:
- image references are a pain (linking mutable external sources), probably we should just discourage in this repository. Images can be in the linked discussions and the aip should be lean.
- upload to thegraph/pinata only - we might wanna add crust or some other provider as well
- the uploaded ipfs has [a lot of wase included](https://github.com/aave/aip), `status`, `created`, `updated`, `preview` are all fields that no ui in circulation currently renders.
- ^^ there's also a `basename` field included which is just the filename, this is not only unnecessary, but also breaks the hash when moving files

Things to consider:
- where to locate these files? consider #84, would actually be nice to colocate

**Comment by sakulstra** [comment]
Just putting some thoughts here:

Copying ipfs hashes from repo to repo is quite error prone.
Therefore putting the ipfs upload here directly makes a lot of sense.

#### Things we should discuss and decide before moving forward though:
- [ ] where do we want to pin ipfs files?
Aave does pinata & thegraph, but e.g. crust might be a reasonable alternative as well.
- [ ] will we continue to transform markdown to json?
The aave interface supports both ways now, i don't really see the benefit of doing it. Tally supports both as well.
- [ ] where should the `md` file be located?
As we currently have a proposal centric structure i'd say putting into the proposal folder seems legit?

#### How should the flow look like?
Currently proposals are created like this:
```
GovHelpers.createProposal(
   payloads,
   0x05097b8a0818a75c1db7d54dfd0299581cac0218a058017acb4726f7cc49657e // TODO: Replace with actual hash
);
```
Issues like https://app.aave.com/governance/proposal/205/ happen when:
- ppl copy the script and forget to replace the hash
- copy the wrong hash

Therefore I'd suggest the following solution:
```
GovHelpers.createProposal(
   payloads,
   _ipfsHash(filepath)
);
```
where `_ipfsHash` would be a function returning the hash for the file (probably using `ffi` + some js). In addition `_ipfsHash` could emit the file content as string so ppl can review when submitting the proposal creation.

**Comment by reem** [comment]
In this WIP tool https://github.com/GauntletNetworks/aave-proposals/pull/2 I added a `upload-ipfs` command which operates on a frontmatter-annotated markdown file, example https://github.com/GauntletNetworks/aave-proposals/blob/21912b815f5bd07ad7a7a573b7fd534c7eee2225/specs/description20230329.md and pins to pinata/the graph while outputting the hash, encoded hash, pinata link, and aave ipfs preview links

This is done from external typescript though rather than being fired from solidity, so not exactly the same approach

Also been thinking about how to auto populate this into the CreateProposal script but don't have anything working there yet

**Comment by sakulstra** [comment]
When thinking about the flow i think it would make sense for `_ipfsHash` to just use sth like https://github.com/aave/aip/blob/main/scripts/aip-uploader.ts#L11 and only generate the hash without uploading.

Otherwise, assuming ppl iterate based on feedback they or we would spam ipfs with x versions.
Uploading should imo be done one the ci. Should be relatively easy to check changed  `*.md` on merges to `main` and just upload them.  As we obviously want ppl to be able to use this outside of our ci, probably a look like the gauntlet one would be usefull (ci might even use it). Not sure if it makes sense to start having js scripts here or better to incorporate in sth like `reports-engine` or `aave-tenderly-cli` ... probably makes kinda sense to consolidate the js tooling a bit anyways.

**Comment by sakulstra** [comment]
A very initial version has been merged here:
Feel free to test https://github.com/bgd-labs/aave-proposals/pull/150
